### PR TITLE
feat: add typechain support to factory functions

### PR DESCRIPTION
**Pull request by TomAFrench**
Following on from #4, I've added the same typechain support for contract factories and also applied these types to the tests.

### CODE REVIEW

**Comment by wighawag** [comment]
Cool, thanks for adding the types to the tests. this is very useful.
Could you remove the typechain via .gitignore (and if needed ensure they are generated before running the test) ?

**Comment by wighawag** [comment]
Thanks @TomAFrench

By the way, I am planning to move `hardhat-deploy-ethers` away from being a fork of https://github.com/nomiclabs/hardhat/tree/master/packages/hardhat-ethers

The plan is to make `hardhat-deploy-ethers` an extension of `hardhat-ethers` 
It is not fully possible due to some missing features in hardhat in regard to plugin capabilities

Why I mention that here, is that once `hardhat-deploy-ethers` become simply an extension to add `hardhat-deploy` specific function like `ethers.getContract` the other functions will be coming from `hardhat-ethers` and so the changes made here and in the other PR, would have to be ported over to `hardhat-ethers`

**Comment by heri16** [comment]
@wighawag Has this PR been released on npm?

**Comment by wighawag** [comment]
@heri16 thanks for the reminder

I just published "0.3.0-beta.8" that contains it

**Pull request merged**
